run:
  timeout: 5m
  go: "1.24"

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - errcheck
    - gosimple

issues:
  exclude-rules:
    # Exclude test files from certain checks
    - path: "_test\\.go"
      linters:
        - errcheck
        - gosec
    # Exclude generated or legacy files
    - path: "test_helpers\\.go"
      linters:
        - unused
    # Allow dot imports in test files for Gomega
    - path: "_test\\.go"
      text: "dot imports"

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kairos-io/kairos/provider-kubeadm
  misspell:
    locale: US
  unused:
    check-exported: false