#cloud-config
# Minimal Kairos configuration for worker node
# IMPORTANT: Use the same control_plane_host as your master node
hostname: worker-{{ trunc 4 .MachineID }}

install:
  device: "auto"
  auto: true
  reboot: true

users:
  - name: kairos
    passwd: kairos
    groups:
      - admin


cluster:
  cluster_token: "your-cluster-token-here"  # Use the same string as your master node
  control_plane_host: 192.168.122.71  # ← SAME IP AS YOUR MASTER NODE
  role: worker

write_files:
- path: /etc/containerd/config.toml
  permissions: "0644"
  content: |
    version = 2
    root="/opt/containerd"
    imports = ["/etc/containerd/conf.d/*.toml"]

    [plugins]
      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "k8s.gcr.io/pause:3.6"
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            BinaryName = "/opt/bin/runc"
            SystemdCgroup = true
        [plugins."io.containerd.grpc.v1.cri".registry]
          config_path = "/etc/containerd/certs.d"
        [plugins."io.containerd.grpc.v1.cri".containerd]
          discard_unpacked_layers = false

stages:
  initramfs:
  - users:
      kairos:
        groups:
          - sudo
        passwd: kairos
  - commands:
    # Disable firewalld to prevent Kubernetes networking issues
    - systemctl disable --now firewalld
    # Create containerd registry config directory
    - mkdir -p /etc/containerd/certs.d
  boot:
  - commands:
    # Restart containerd to pick up new registry configuration
    - systemctl restart containerd
