name: Pull Request

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Download dependencies
        run: go mod download
      - name: Run unit tests
        run: go test -v ./tests/unit/...
      - name: Run integration tests
        run: go test -v ./tests/integration/...
      - name: Run coverage verification
        run: go test -v ./tests/unit/coverage_verification_test.go

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: earthly --ci +lint

  build-provider-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: earthly/actions-setup@v1
        with:
          version: "v0.6.30"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - run: earthly --ci --output +build-provider-package